spring:
  h2:
    console:
      enabled: true

  datasource:
    username: sa
    password:
    url: jdbc:h2:tcp://localhost:1521/test
    driver-class-name: org.h2.Driver

  jpa:
    properties:
      hibernate:
        use_sql_comments: true
        format-sql: true
    hibernate:
      ddl-auto: create

logging:
  level:
    org.hibernate.SQL: debug

decorator:
  datasource:
    p6spy:
      enable-logging: true
