spring:

  h2:
    console:
      enabled: true

  datasource:
    username: sa
    password:
    url: jdbc:h2:tcp://localhost:1521/test
    driver-class-name: org.h2.Driver

  jpa:
    properties:
      hibernate:
        use_sql_comments: true
        format-sql: true
        show_sql: true;
    hibernate:
      ddl-auto: create
      default_batch_fetch_size: 100
    open-in-view: true

logging:
  level:
    org.hibernate.SQL: debug

decorator:
  datasource:
    p6spy:
      enable-logging: true

